hackday_scaffold_homepage:
    pattern:  /asdf/{name}
    defaults: { _controller: HackdayScaffoldBundle:Default:index }

controller:
    resource: "@HackdayScaffoldBundle/Controller/"
    type: annotation
