hackday_scaffold_homepage:
    pattern:  /asdf/{name}
    defaults: { _controller: HackdayScaffoldBundle:Default:index }

scaffold:
    resource: "@HackdayScaffoldBundle/Controller/CategoryController.php"
    prefix: /category
    type: annotation