parameters:
#    hackday_scaffold.example.class: Hackday\ScaffoldBundle\Example

services:
#    hackday_scaffold.example:
#        class: %hackday_scaffold.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
